name: flutter_live_logger
description: Real-time logging solution for Flutter applications with offline support and web dashboard
version: 0.1.0
homepage: https://github.com/example/flutter_live_logger
repository: https://github.com/curogom/flutter_live_logger
issue_tracker: https://github.com/curogom/flutter_live_logger/issues
documentation: https://github.com/curogom/flutter_live_logger#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  crypto: ^3.0.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  test: ^1.24.6

flutter: 