name: flutter_live_logger
description: Real-time logging solution for Flutter applications with offline support and web dashboard
version: 0.1.0
homepage: https://github.com/example/flutter_live_logger
repository: https://github.com/curogom/flutter_live_logger
issue_tracker: https://github.com/curogom/flutter_live_logger/issues
documentation: https://github.com/curogom/flutter_live_logger#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.6

flutter: 