name: flutter_live_logger_dashboard
description: >-
  Real-time web dashboard for Flutter Live Logger. 
  Provides live log monitoring, analytics, and performance insights 
  through a beautiful Flutter Web interface with WebSocket streaming.
version: 0.2.0
homepage: https://github.com/curogom/flutter_live_logger
repository: https://github.com/curogom/flutter_live_logger

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Core 로깅 라이브러리
  flutter_live_logger: ^0.2.0

  # HTTP 클라이언트
  http: ^1.1.2

  # 상태 관리
  flutter_riverpod: ^2.4.9

  # 차트 라이브러리
  fl_chart: ^0.68.0

  # 데이터 테이블
  data_table_2: ^2.5.9

  # 데이터베이스
  drift: ^2.13.2
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.0
  
  # 웹소켓 클라이언트
  web_socket_channel: ^2.4.0

  # HTTP 서버
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.13.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true 