name: flutter_live_logger
description: Production-ready real-time logging for Flutter with HTTP, File, Memory transports, offline support, and developer-friendly APIs.
version: 0.1.1+1

# Repository and documentation links
homepage: https://github.com/curogom/flutter_live_logger
repository: https://github.com/curogom/flutter_live_logger
issue_tracker: https://github.com/curogom/flutter_live_logger/issues
documentation: https://github.com/curogom/flutter_live_logger#-documentation

# Package metadata for better discoverability
topics:
  - logging
  - flutter
  - debugging
  - monitoring
  - analytics

# Platform compatibility
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Flutter and Dart version constraints
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

# Dependencies
dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  sqflite: ^2.3.0
  # Web Dashboard Backend Dependencies
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  shelf_cors_headers: ^0.1.5
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  # Web Dashboard Frontend Dependencies  
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  fl_chart: ^0.66.0
  data_table_2: ^2.5.9
  web_socket_channel: ^2.4.0

# Development dependencies
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.6
  # Additional test dependencies for web dashboard
  drift_dev: ^2.14.1
  riverpod_generator: ^2.3.9
  fake_async: ^1.3.1

flutter: 