name: flutter_live_logger
description: Production-ready real-time logging for Flutter with HTTP, File, Memory transports, offline support, and developer-friendly APIs.
version: 0.1.1+1

# Repository and documentation links
homepage: https://github.com/curogom/flutter_live_logger
repository: https://github.com/curogom/flutter_live_logger
issue_tracker: https://github.com/curogom/flutter_live_logger/issues
documentation: https://github.com/curogom/flutter_live_logger#-documentation

# Package metadata for better discoverability
topics:
  - logging
  - flutter
  - debugging
  - monitoring
  - analytics

# Platform compatibility
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Flutter and Dart version constraints
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

# Dependencies
dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  sqflite: ^2.3.0

# Development dependencies
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.6

flutter: 