[files]
extend-exclude = [
  "*.g.dart",
  "*.freezed.dart", 
  "*.gen.dart",
  "pubspec.lock",
  "CHANGELOG.md",
  "*.lock",
  "*.log",
  "coverage/*",
  ".dart_tool/*",
  "build/*",
  ".git/*"
]

[default]
# 기본 언어는 영어, 한국어 텍스트는 무시
locale = "en"

extend-ignore-identifiers-re = [
    # Technical terms and proper nouns
    "FlutterLiveLogger",
    "SQLite",
    "pub.dev",
    "dartdoc",
    "sqflite",
    "codecov", 
    "Crashlytics",
    "Firebase",
    "WebSocket",
    "GitHub",
    "curogom",
    # Korean words that might be flagged
    "로깅",
    "로그",
    "프로덕션",
    "애플리케이션",
    "디버깅",
    # Common abbreviations
    "async",
    "await",
    "impl",
    "config",
    "init",
    "params",
    "nullable",
    "stacktrace"
]

[default.extend-words]
# 프로젝트 특정 용어들
FlutterLiveLogger = "FlutterLiveLogger"
Codecov = "Codecov"
dartdoc = "dartdoc"

# 한국어 용어들 (맞춤법 검사 제외)
"기여자" = "기여자"
"행동" = "행동" 
"강령" = "강령"
"서약" = "서약"
"커뮤니티" = "커뮤니티"
"리더" = "리더" 